[package]
name = "validating_envs"
version = "0.1.0"
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.96"
envoke = { path = "../../modules/envoke" }
temp-env = "0.3.6"
