[package]
name = "try_parsing_envs"
version = "0.1.0"
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
anyhow = "1.0.97"
envoke = { path = "../../modules/envoke" }
temp-env = "0.3.6"
uuid = { version = "1.16.0", features = ["v4"] }
