[package]
name = "from_dotenv"
version = "0.1.0"
repository.workspace = true
license.workspace = true
edition.workspace = true

[dependencies]
envoke = { path = "../../modules/envoke" }
temp-env = "0.3.6"
